version: '3.1'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${SENHA_ROOT:-example}
      MARIADB_DATABASE: ${NOME_BANCO:-amigooculto}
    ports:
      - 3306:3306
